# Done to increase the memory available to gradle.
# add-exports are needed for spotless to work on new Javas
org.gradle.jvmargs=-Xmx1G \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

mc_version=1.21.11
build_number=94.1
group=vazkii.patchouli
mod_name=Patchouli

fabric_loader_version=0.19.3
fabric_api_version=0.141.4+1.21.11
jei_version=27.17.0.49
rei_version=21.11.816+fabric
cloth_config_version=21.11.153
