name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches:
      - port/1.21.11-fabric
    paths:
      - web/**
      - .github/workflows/deploy_docs.yml

permissions:
  contents: write

concurrency:
  group: deploy-docs
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: yarn
          cache-dependency-path: web/yarn.lock

      - name: Install dependencies
        run: corepack yarn install --frozen-lockfile
        working-directory: web

      - name: Build website
        run: corepack yarn build
        working-directory: web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/build
